version: '3'

services:
  db:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
     - sousei_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: python_test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: sousei_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOSTS: 'db'
    ports:
    - 8080:80

  nginx:
    container_name: nginx_flask
    build:
      context: .
      dockerfile: ./docker/Dockerfile_nginx
    ports:
      - 5002:80
      - 5001:5000
    depends_on:
      - db

volumes:
  sousei_db:

