version: '3'

services:
  db:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
     - sousei_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sousei_db
      MYSQL_USER: team4
      MYSQL_PASSWORD: team4
    ports:
      - 3306:3306
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD

  phpmyadmin:
    container_name: sousei_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOSTS: 'db'
    ports:
    - 8080:80

  nginx:
    container_name: nginx_flask
    build:
      context: .
      dockerfile: ./docker/Dockerfile_nginx
    volumes:
      - .:/var/flaskapp
    command: /bin/bash /var/flaskapp/docker/run.sh
    tty: true
    restart: always
    ports:
      - 13431:80
      - 37564:5000
    depends_on:
      db:
        condition: service_healthy

volumes:
  sousei_db:

