FROM ubuntu:20.04

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y install python
RUN apt-get -y install python3-pip
RUN apt-get -y install uwsgi
RUN apt-get -y install uwsgi-plugin-python
RUN apt-get -y install locales-all
RUN pip3 install --upgrade pip && pip install flask  && pip install sqlalchemy && pip install flask-sqlalchemy
COPY ./ /var/flask_app/
COPY ./docker/default.conf /etc/nginx/conf.d/default.conf
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
CMD ["bash","/var/flask_app/docker/run.sh"]
