FROM nginx:latest

RUN apt-get update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN apt-get -y install uwsgi
RUN apt-get -y install uwsgi-plugin-python3
RUN apt-get -y install locales-all
RUN apt-get -y install procps
RUN pip3 install --upgrade pip && pip3 install flask uwsgi sqlalchemy flask-sqlalchemy flask-caching flask-login flask-marshmallow mysql-connector-python marshmallow DateTime marshmallow-sqlalchemy
COPY ./ /var/flask_app/
COPY ./docker/default.conf /etc/nginx/conf.d/default.conf
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
