FROM nginx:latest

RUN apt-get update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN apt-get -y install uwsgi
RUN apt-get -y install uwsgi-plugin-python3
RUN apt-get -y install locales-all
RUN apt-get -y install procps
RUN pip3 install --upgrade pip && pip3 install flask && pip3 install uwsgi && pip3 install sqlalchemy && pip3 install flask-sqlalchemy && pip3 install mysql-connector-python
COPY ./ /var/flask_app/
COPY ./docker/default.conf /etc/nginx/conf.d/default.conf
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
CMD ["/bin/bash","/var/flask_app/docker/run.sh"]
